" common settings
set ruler         " show the cursor position all the time
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands
set number        " Make line numbers
set t_Co=256      " Tell Vim that terminal supports 256

" do not make backup files
set nobackup
set nowritebackup

" Make sure to use h,j,k,l
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

" Make it obvious where 100 characters is
if exists('+colorcolumn')
  set colorcolumn=100
endif

" Turn on syntax highlighting
syntax on

" Add the bundles
source ~/.dotfiles/vim-dotfiles/vimrc.bundles

" Show hidden files in NERDTree and CTRLp
let NERDTreeShowHidden=1
let g:ctrlp_show_hidden=1

" Autoload vimrc when it changes
augroup myvimrc
  " au!
  au BufWritePost .vimrc,vimrc so $MYVIMRC
augroup end

" Integrate airline with the powerline fonts
let g:airline_powerline_fonts = 1

" Allow jsx syntax highlighting on js files
let g:jsx_ext_required = 0

" Common syntastic settings
let g:airline#extensions#syntastic#enabled = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" let airline#extensions#syntastic#error_symbol = 'E:'
" let airline#extensions#syntastic#stl_format_err = '%E{[%e(#%fe)]}'
" let airline#extensions#syntastic#warning_symbol = 'W:'
" let airline#extensions#syntastic#stl_format_err = '%W{[%w(#%fw)]}'
      

let g:syntastic_javascript_checkers = ['eslint']
