source ~/.profile

ZSH_THEME="agnoster"
DISABLE_AUTO_TITLE="true"
DEFAULT_USER="max"


# run the oh-my-zsh src
export ZSH=$HOME/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# oh-my-zsh plugins
plugins=(osx)

# alias to reset zsh
alias rl='source ~/.zshrc && echo "Reloaded zshrc!\n"'

# alias to run npm modules
alias npm-exec='PATH=$(npm bin):$PATH'

