# make current working directory show up
# export PS1="[%* - %D] %d %% "

# make asdf work with homebrew
source /usr/local/opt/asdf/asdf.sh

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
DISABLE_AUTO_TITLE="true"
source $ZSH/oh-my-zsh.sh
DEFAULT_USER="max"

alias rl='source ~/.zshrc && echo "Reloaded zshrc!\n"'

# oh-my-zsh plugins
plugins=(brew node npm)
