# make current working directory show up
# export PS1="[%* - %D] %d %% "

# make asdf work with homebrew
source /usr/local/opt/asdf/asdf.sh

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"
source $ZSH/oh-my-zsh.sh

alias rl='source ~/.zshrc && echo "Reloaded zshrc!\n"'

